### ISSUE TITLE
Registry ID of io_connect_t

### ISSUE THREAD

**Issue by Siguza** [bazad/bazad.github.io#1]
Hey, just came across your "Live kernel introspection on iOS", where you say:

> Despite searching far and wide, I could not find an official API to retrieve the registry entry ID associated with an `io_connect_t` object returned by `IOServiceOpen`. This was the simplest and most flexible workaround I could find.

Such an API does indeed not seem to exist, but the way I do this is to first retrieve an `io_object_t` handle to my `io_connect_t` object (i.e. a mach port with the same backing object, but type `IKOT_IOKIT_OBJECT` rather than `IKOT_IOKIT_CONNECT`), with which I can actually work then. The way I do this is by iterating over all children of the service I spawned my client on and getting their properties, which contain the PID that spawned them, e.g.:

    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
    <dict>
        <key>IOUserClientCreator</key>
        <string>pid 91, securityd</string>
    </dict>
    </plist>

This seems to be all the information you get that would connect the two handles. As long as your process only spawns a single client that is straightforward, but otherwise you need to always get the object handle before opening another client, and keep a list of all handles belonging to your process to compare against. Tedious, but should protect against race conditions. :)

**Comment by bazad** [comment]
Hey Siguza, thanks for the tip! I actually used to get the registry ID in almost exactly that way, but I changed it in memctl commit 8633d96 because IORegistryEntryCreateCFProperty() isn't available in the application sandbox for mach_portal_memctl, and I couldn't break out of the sandbox until after I established a kernel function call primitive.

**Comment by Siguza** [comment]
Oh, that's been killed? Well never mind then...
